"""User-facing text, in one place.

Everything a reader sees lives here so a new language is a dictionary, not a
rewrite. The keys are stable identifiers; the values are format strings.

Detection data is deliberately *not* here. The maintenance-page markers in
`evidence.py` match what Korean sites actually print, and translating them
would break detection rather than localise it — a Turkish deployment adds
Turkish markers alongside, it does not replace the Korean ones.
"""

from __future__ import annotations

from functools import lru_cache
from collections.abc import Callable

DEFAULT_LANGUAGE = "ko"

CATALOGUE: dict[str, dict[str, str]] = {
    "ko": {
        # -- chrome ---------------------------------------------------------
        "nav.overview": "개요",
        "nav.signals": "신호함",
        "nav.companies": "기업",
        "nav.vendors": "솔루션",
        "nav.manage": "관리",
        "nav.fingerprints": "지문",
        "fp.title": "벤더 지문",
        "fp.lede": "판정의 근거가 되는 패턴들. 편집은 YAML에서 하고, 여기서는 보고 시험합니다.",
        "fp.try": "패턴 시험해보기",
        "fp.try_hint": "지금까지 수집한 모든 증거에 대조합니다. 사이트는 방문하지 않습니다.",
        "fp.try_run": "대조",
        "fp.try_result": "{scanned}개 스캔 중 {hits}곳에서 일치",
        "fp.try_none": "{scanned}개 스캔 어디에도 걸리지 않았습니다.",
        "fp.try_check": "일치한 값이 정말 그 벤더의 것인지 확인하세요. 파일명이나 짧은 전역변수는 남의 것에 걸리기 쉽습니다.",
        "fp.try_this": "대조",
        "fp.registry": "등록된 지문",
        "fp.search": "벤더 이름 또는 id",
        "fp.search_run": "찾기",
        "fp.signal_count": "시그널 {n}개",
        "fp.edit_where": "지문 추가·수정은 fingerprints/*.yaml에서 합니다. 저장 후 redetect를 실행하면 과거 스캔 전부가 새 지문으로 재판정됩니다.",
        "nav.signout": "로그아웃",
        "login.title": "로그인",
        "login.hint": "설정에 지정된 접근 토큰을 입력하세요.",
        "login.token": "접근 토큰",
        "login.submit": "들어가기",
        "login.bad": "토큰이 맞지 않습니다.",
        "manage.title": "워치리스트 관리",
        "manage.lede": "여기서 저장한 내용이 다음 스캔에 그대로 반영됩니다. 파일을 고칠 필요가 없습니다.",
        "manage.add": "새 기업 추가",
        "manage.edit_one": "{id} 수정",
        "manage.edit": "수정",
        "manage.save": "저장",
        "manage.pause": "중지",
        "manage.resume": "재개",
        "manage.on": "활성",
        "manage.paused": "중지됨",
        "manage.scan_all": "전체 스캔 예약",
        "manage.scan_one": "스캔",
        "manage.watching": "관측 중인 기업 {n}곳",
        "manage.in_progress": "run {run} 진행 중 — {done}/{total}",
        "manage.field.id": "id",
        "manage.field.id_hint": "이력의 키입니다. 한 번 정하면 바꾸지 마세요.",
        "manage.field.company_en": "영문명",
        "manage.field.tier": "구분",
        "manage.field.enabled": "스캔 대상에 포함",
        "manage.field.urls_hint": "한 줄에 하나. 첫 번째가 대표 URL입니다.",
        "manage.no_industries": "업종이 하나도 없습니다",
        "manage.no_industries_hint": "기업은 업종에 속해야 합니다. 아래에서 업종을 먼저 만들거나, 터미널에서 radar watchlist import targets.yaml 로 예시를 불러오세요.",
        "manage.industry_add": "업종 추가",
        "manage.industry_count": "현재 {n}개",
        "manage.industry_label": "표시 이름",
        "manage.robots": "robots.txt",
        "manage.robots.respect": "사이트의 robots.txt를 따른다 (기본)",
        "manage.robots.override": "이 기업은 예외로 둔다",
        "manage.robots.reason": "예외 사유 (예외를 고르면 필수)",
        "manage.robots.hint": "예외는 기업 단위 결정이고 사유가 남습니다. 나중에 누구든 왜 그랬는지 확인할 수 있어야 합니다.",
        "manage.robots.respect_chip": "준수",
        "manage.robots.turned_away": "사이트가 거부",
        "manage.turned_away_note": "{n}곳이 robots.txt로 우리를 거부하고 있습니다. 관측할 근거가 있다면 기업별로 예외를 두되, 사유를 남기세요.",
        "manage.robots.override_chip": "예외",
        "run.counts": "완료 {done}/{total} · 대기 {pending} · 진행 {running} · 실패 {failed}",
        "run.waiting": "아직 아무 워커도 이 작업을 가져가지 않았습니다",
        "run.worker_hint": "이 실행의 작업은 큐에 들어갔습니다. 브라우저를 돌릴 컴퓨터에서 워커를 실행하세요.",
        "job.pending": "대기",
        "job.claimed": "진행 중",
        "job.done": "완료",
        "job.failed": "실패",
        "nav.ops": "운영",
        "ops.title": "운영",
        "ops.lede": "터미널에서 하던 일을 여기서 시킵니다. 대시보드는 요청만 남기고 워커가 처리합니다.",
        "ops.worker.alive": "워커 {name} · {ago}초 전 활동",
        "ops.worker.stale": "워커가 응답하지 않습니다 · 마지막 활동 {at}",
        "ops.worker.none": "워커 기록이 없습니다 · bin/radarctl status 로 확인하세요",
        "ops.scan": "스캔",
        "ops.scan.note": "스캔은 큐에 들어가고 워커가 브라우저로 방문합니다. 진행 상황은 실행 페이지에서 봅니다.",
        "ops.scan.due": "주기 도래분 {n}곳",
        "ops.scan.tier": "{tier} {n}곳",
        "ops.scan.all": "전체 {n}곳",
        "ops.scan.nothing": "지금 스캔할 대상이 없습니다",
        "ops.tasks": "작업",
        "ops.tasks.note": "각 버튼은 작업 하나를 큐에 넣습니다. 결과는 아래 목록에서 열어 봅니다.",
        "ops.task.digest": "digest 생성",
        "ops.task.digest.hint": "신호와 실행 상태 요약을 data/logs/에 씁니다",
        "ops.task.redetect": "재판정",
        "ops.task.redetect.hint": "현재 지문으로 저장된 모든 증거를 다시 판정합니다. 사이트 방문 없음",
        "ops.task.notify": "알림 발송",
        "ops.task.notify.hint": "아직 보내지 않은 신호를 웹훅으로 보냅니다",
        "ops.task.notify_dry": "알림 미리보기",
        "ops.task.notify_dry.hint": "보낼 신호만 나열하고 보내지 않습니다",
        "ops.task.hygiene": "워치리스트 위생",
        "ops.task.hygiene.hint": "연속 실패한 URL을 찾습니다. 죽은 도메인이나 이전한 사이트",
        "ops.task.backup": "DB 백업",
        "ops.task.backup.hint": "backups/에 스냅샷을 만들고 14개만 남깁니다",
        "ops.queued": "작업 #{id} ({kind}) 큐에 넣었습니다. 워커가 곧 처리합니다.",
        "ops.history": "최근 작업",
        "ops.history.none": "아직 작업이 없습니다.",
        "ops.runs": "진행 중인 실행",
        "task.kind.digest": "digest",
        "task.kind.redetect": "재판정",
        "task.kind.notify": "알림 발송",
        "task.kind.hygiene": "워치리스트 위생",
        "task.kind.backup": "DB 백업",
        "task.state.pending": "대기",
        "task.state.running": "진행 중",
        "task.state.done": "완료",
        "task.state.failed": "실패",
        "task.title": "작업 #{id} · {kind}",
        "task.requested": "요청 {at} · {by}",
        "task.waiting": "워커가 가져가기를 기다리는 중입니다. 이 페이지는 자동으로 갱신됩니다.",
        "task.output": "출력",
        "task.no_output": "출력 없음",
        "common.seconds": "초",
        "footer.readonly": "판정은 관측에서만 나옵니다 · 스캔은 큐에 쌓이고 워커가 처리합니다",
        "common.all": "전체",
        "common.none": "없음",
        "common.company": "기업",
        "common.industry": "업종",
        "common.vendor": "벤더",
        "common.vendors": "벤더",
        "common.companies": "기업",
        "common.company_count": "기업 수",
        "common.share": "점유",
        "common.state": "상태",
        "common.change": "변화",
        "common.score": "점수",
        "common.time": "시각",
        "common.status": "상태",
        "common.run": "실행",
        "common.note": "비고",
        "common.layer": "층",
        "common.strength": "강도",
        "common.pattern": "패턴",
        "common.observed": "실제 관측값",
        "common.evidence_layers": "증거 층",
        "common.and_more": "외 {n}곳",
        # -- verdicts and states --------------------------------------------
        "verdict.DETECTED": "확정",
        "verdict.PROBABLE": "추정",
        "state.NEW": "신규",
        "state.REAPPEARED": "재등장",
        "state.STABLE": "유지",
        "state.BASELINE": "기준선",
        "state.REMOVAL_CANDIDATE": "이탈 후보",
        "state.REMOVED": "이탈 확인",
        "status.OK": "정상",
        "status.BLOCKED": "차단됨",
        "status.TIMEOUT": "시간초과",
        "status.NAV_FAILED": "접속실패",
        "status.BROWSER_ERROR": "브라우저오류",
        "status.THIN": "빈 페이지(점검 등)",
        "status.SKIPPED_BY_ROBOTS": "robots.txt 요청으로 건너뜀",
        "status.PARTIAL": "부분 로드(비교 제외)",
        "status.unscanned": "미스캔",
        "kind.HOME_MIGRATION": "자사 → 타사 교체",
        "kind.HOME_REMOVAL": "자사 이탈 위험",
        "kind.COMPETITOR_MIGRATION": "벤더 교체",
        "kind.COMPETITOR_REMOVAL": "벤더 이탈 정황",
        "kind.GREENFIELD": "미보유 · 공략 가능",
        "kind.COMPETITOR_NEW": "벤더 신규 진입",
        "kind.HOME_NEW": "자사 신규 도입",
        "kind.HOST_CHANGED": "착지 사이트 변경",
        "category.engagement": "engagement",
        "category.experimentation": "A/B·실험",
        "category.analytics": "애널리틱스",
        "category.attribution": "어트리뷰션",
        "category.advertising": "광고",
        "category.platform": "플랫폼·인프라",
        # -- overview -------------------------------------------------------
        "overview.latest_run": "최근 실행 <b>run {run}</b> · {when} · {scans}건 스캔 · 지문 {fingerprints}종",
        "overview.no_runs": "아직 실행 기록이 없습니다. <code>{command}</code>를 먼저 실행하세요.",
        "overview.card.registered": "등록 기업",
        "overview.card.holders": "engagement 보유",
        "overview.card.greenfield": "미보유 (greenfield)",
        "overview.card.unjudged": "판정 불가",
        "overview.signals_all": "전체 {n}건 →",
        "overview.no_change": "변화 신호 없음.",
        "overview.by_industry": "업종별",
        "overview.engagement_share": "engagement 점유",
        "overview.all_vendors": "전체 솔루션 →",
        "overview.col.holders": "보유",
        "overview.col.greenfield": "미보유",
        "overview.col.unjudged": "판정불가",
        "overview.col.held_vendors": "보유 벤더",
        "overview.statement": "정상 판정된 {judged}곳 가운데 <em>{greenfield}곳</em>은 engagement 플랫폼 없이 마케팅을 운영하고 있습니다.",
        "overview.statement.empty": "아직 판정된 기업이 없습니다. 첫 스캔이 끝나면 여기에 요약이 나타납니다.",
        "overview.signals_line": "변화 신호 {n}건",
        "companies.pick_industry": "모든 업종",
        # -- signals --------------------------------------------------------
        "signals.title": "신호함",
        "signals.empty": "해당하는 신호가 없습니다.",
        "signals.maturity": "MarTech {total}종 · 광고 {advertising} · 애널리틱스 {analytics}",
        "signals.maturity.attribution": " · 어트리뷰션 {n}",
        "signals.maturity.experimentation": " · A/B {n}",
        "signals.maturity.score": " · 성숙도 {score}",
        "signals.change_detail": "{name} — run {since}부터 {streak}회 연속 (판정 가능 실행 {judged}회 기준)",
        "signals.quiet.title": "임계값 미달",
        "signals.quiet.note": "engagement 플랫폼은 없지만 MarTech 운영 규모가 작아 신호로 올리지 않은 기업입니다. 숨기지 않고 표시합니다 — 조용히 잘라내면 \"확인했는데 없더라\"로 읽히기 때문입니다.",
        "signals.quiet.score": "성숙도 {score}",
        "signals.unjudged.title": "판정 불가",
        "signals.unjudged.note": "한 번도 정상 스캔되지 않아 어떤 신호도 만들지 않은 기업입니다. <b>미보유(greenfield)와 다릅니다.</b>",
        # -- companies ------------------------------------------------------
        "companies.title": "기업 {n}곳",
        "companies.filter.holders": "engagement 보유",
        "companies.filter.greenfield": "미보유",
        "companies.filter.moved": "변화 있음",
        "companies.filter.unjudged": "판정 불가",
        "companies.none": "조건에 맞는 기업이 없습니다.",
        "companies.chip.greenfield": "미보유",
        "companies.chip.judged": "판정 가능",
        "companies.chip.unjudged": "{status} · 판정 불가",
        "companies.chip.paused": "모니터링 중지",
        "companies.chip.off_domain": "다른 도메인 착지",
        "company.off_domain": "최근 정상 관측이 감시 URL과 다른 도메인({host})에 착지했습니다. 아래 스택은 이 기업의 것이 아닐 수 있습니다. 워치리스트 URL을 확인하세요.",
        "company.host_shift": "run {run}부터 착지가 {previous} 에서 {current} 로 바뀌었습니다. 그 이전 이력과는 비교하지 않습니다.",
        "common.landing": "착지",
        # -- company detail --------------------------------------------------
        "company.never_judged": "이 기업은 아직 정상 스캔된 적이 없습니다 (최근 상태: {status}). <b>스택을 보고할 수 없습니다</b> — 아무것도 안 쓴다는 뜻이 아닙니다.",
        "company.signals": "신호",
        "company.brief": "brief 보기",
        "company.brief.title": "{company} brief",
        "company.brief.note": "메일에 인용할 수 있는 관측 사실의 전체 목록입니다. 여기 없는 것은 쓰지 않습니다.",
        "company.brief.unusable": "정상 관측이 없어 brief를 만들 수 없습니다. 이 기업에 대한 콜드메일은 쓰지 마십시오.",
        "company.scan_now": "지금 스캔",
        "company.stack": "현재 스택",
        "company.stack.summary": "MarTech {total}종 · 성숙도 {score}",
        "company.stack.hint": "각 항목을 펼치면 그렇게 판정한 실제 증거를 볼 수 있습니다.",
        "company.no_direct": "직접 증거 없음",
        "company.mention_only": "언급만 — 실행 확인 안 됨",
        "company.seen_on": "{url} 에서 관측",
        "company.streak": " · run {judged}회 중 {streak}회 연속",
        "company.timeline": "타임라인",
        "company.timeline.excluded": "판정 불가 — 이력에서 제외",
        "company.scans": "스캔 기록",
        "company.col.urls": "URL",
        # -- vendors ---------------------------------------------------------
        "vendors.title": "솔루션 점유",
        "vendors.basis": "정상 스캔된 {n}개 기업 기준.",
        "vendors.include_unseen": "미검출 지문 포함",
        "vendor.detected_in": "{n}개 기업에서 검출",
        "vendor.users": "사용 기업",
        "vendor.fingerprint": "지문",
        "vendor.none": "이 벤더는 아직 어떤 기업에서도 검출되지 않았습니다.",
        # -- reports (digest / brief) ----------------------------------------
        "digest.title": "MarTech Deal Radar — {date}",
        "notify.header": "MarTech Radar — 새 시그널 {n}건",
        "ack.ack": "확인",
        "ack.dismiss": "무시",
        "ack.clear": "해제",
        "ack.acked": "후속 중",
        "ack.dismissed": "무시됨",
        "ack.dismissed_count": "무시된 시그널 {n}건 — 보기",
        "ack.hide_dismissed": "무시된 시그널 숨기기",
        "digest.hygiene": "도달 실패 반복 (도메인 점검 필요, {n}건):",
        "company.identifiers": "계정 식별자",
        "company.identifiers.note": "스캔에서 관찰된 벤더 계정 ID — 어떤 계약이 붙어 있는지까지 보여줍니다.",
        "brief.identifiers": "## 관찰된 계정 식별자",
        "notify.more": "…외 {n}건 (대시보드 신호함에서 전체 확인)",
        "digest.latest_run": "최근 실행 run {run} · {when} · {scans}건 스캔 ({statuses})",
        "digest.partial": " — **부분 실행**: 워치리스트 {total}곳 중 {covered}곳만 스캔",
        "digest.partial_note": "아래 현황은 각 기업의 **가장 최근 정상 스캔** 기준이므로 부분 실행에 영향받지 않습니다.",
        "digest.changes": "## 이번 주 변화",
        "digest.no_changes": "- 없음",
        "digest.greenfield": "## 공략 가능 (engagement 미보유 · {n}곳)",
        "digest.quiet": "## 임계값 미달 (참고)",
        "digest.unjudged": "## 판정 불가 — greenfield 아님",
        "brief.unknown_target": "알 수 없는 기업 id: {target_id!r}",
        "brief.never_scanned": "**정상 스캔된 적이 없습니다.** (시도 {scans}회, 최근 상태: {status})",
        "brief.never_scanned.rule": "관측 근거가 없으므로 이 기업에 대한 콜드메일을 작성하지 마십시오.\n'아무것도 안 쓴다'가 아니라 '확인하지 못했다'는 뜻입니다.",
        "brief.urls": "- URL: {urls}",
        "brief.latest": "- 최근 정상 관측: {date} (run {run}), 판정 가능한 실행 {judged}회",
        "brief.host_shift": "- **착지 변경**: run {run}부터 {previous} → {current}. 그 이전 이력과는 비교하지 않음",
        "brief.off_domain": "**최근 정상 관측(run {run})이 감시 URL과 다른 도메인({host})에 착지했습니다.** 이 기업의 관측으로 볼 수 없으므로 스택도 사실도 인용할 수 없습니다. 워치리스트 URL을 확인하세요.",
        "brief.counts": "- 검출된 MarTech {total}종 · 성숙도 점수 {score}",
        "brief.engagement": "## engagement 플랫폼",
        "brief.engagement.none": "- **없음 (greenfield)** — 판정 가능한 {judged}회 실행 모두에서 미검출",
        "brief.engagement.gone": "- **현재 미검출** — {name}: run {since}부터 미검출 ({state}, {streak}회 연속 / 판정 가능 {judged}회). 직전 실행까지는 검출됨",
        "brief.stack": "## 관측된 스택",
        "brief.changes": "## 변화",
        "brief.changes.none": "- 없음 — 판정 가능한 {judged}회 실행에서 동일",
        "brief.facts": "## 메일에 인용 가능한 관측 사실",
        "brief.facts.rule": "다음은 우리가 실제로 관측한 것입니다. 이 목록에 없는 것은 메일에 쓰지 마십시오.",
        "brief.fact.no_engagement": "- engagement/CRM 플랫폼이 검출되지 않음 (판정 가능 {judged}회 실행 전부)",
        "brief.fact.engagement_gone": "- engagement 플랫폼 {name}이(가) 직전 실행까지 검출되다 run {since}부터 미검출 ({streak}회 연속 — 이탈 후보이며 확정 아님)",
        "brief.fact.advertising": "- 광고 픽셀 {n}종 운영",
        "brief.fact.analytics": "- 애널리틱스 도구 {n}종 운영",
        "brief.fact.attribution": "- 모바일 어트리뷰션 {n}종 — 앱 사업 병행 정황",
        "brief.fact.experimentation": "- A/B 테스트 도구 {n}종 — 실험 문화 존재",
        "brief.fact.no_experimentation": "- A/B 테스트 도구 미검출",
        # -- signal headlines -------------------------------------------------
        "signal.home_removal.headline": "{vendor}가 {streak}회 연속 관측되지 않음",
        "signal.home_removal.unconfirmed": " (1회 — 확인 필요)",
        "signal.home_removal.detail": "run {since} 이후 미검출. ",
        "signal.home_removal.confirmed_note": "이탈 확인 임계값 도달.",
        "signal.home_removal.candidate_note": "다음 실행에서 재확인 전까지는 후보 상태.",
        "signal.migration.headline": "{gone} → {arrived} 교체 정황",
        "signal.migration.unconfirmed": " (확인 필요)",
        "signal.migration.detail": "{gone}는 run {gone_since}부터 미검출, {arrived}는 run {arrived_since}부터 검출. 같은 시기에 빠지고 들어왔다.",
        "signal.competitor_removal.headline": "{name} 미검출 {streak}회 연속",
        "signal.competitor_removal.unconfirmed": " (확인 필요)",
        "signal.competitor_removal.detail": "run {since} 이후 미검출. 교체 검토 시점일 수 있음.",
        "signal.arrival.headline": "{name} 신규 검출",
        "signal.host_changed.headline": "착지가 {previous} 에서 {current} 로 바뀜",
        "signal.host_changed.detail": "run {run}부터 다른 사이트에 착지합니다. 그 이전 이력과는 비교하지 않고 벤더 변화 신호도 내지 않습니다. 워치리스트 URL을 확인하세요.",
        "signal.host_changed.off_domain": " 감시 URL의 도메인과도 다르므로 이 관측은 이 기업의 것이 아닐 수 있습니다.",
        "signal.arrival.reappeared": " (재등장)",
        "signal.arrival.detail": "run {since}부터 검출. 직전 실행에는 없었음.",
        "signal.greenfield.headline": "engagement 플랫폼 미검출 · MarTech {total}종 운영 중",
        "signal.greenfield.detail": "광고 픽셀 {advertising}종, 애널리틱스 {analytics}종",
        "signal.greenfield.attribution": ", 어트리뷰션 {n}종",
        "signal.greenfield.experimentation": ", A/B {n}종",
    },
    "en": {
        "nav.overview": "Overview",
        "nav.signals": "Signals",
        "nav.companies": "Companies",
        "nav.vendors": "Vendors",
        "nav.manage": "Manage",
        "nav.fingerprints": "Fingerprints",
        "fp.title": "Vendor fingerprints",
        "fp.lede": "The patterns behind every verdict. Edit them in YAML; read and try them here.",
        "fp.try": "Try a pattern",
        "fp.try_hint": "Matched against every piece of evidence collected so far. No site is visited.",
        "fp.try_run": "Match",
        "fp.try_result": "matched at {hits} of {scanned} scans",
        "fp.try_none": "No match in any of {scanned} scans.",
        "fp.try_check": "Check that each match really belongs to that vendor. Filenames and short globals collide easily.",
        "fp.try_this": "Try",
        "fp.registry": "Registry",
        "fp.search": "vendor name or id",
        "fp.search_run": "Search",
        "fp.signal_count": "{n} signals",
        "fp.edit_where": "Add or change fingerprints in fingerprints/*.yaml. Run redetect afterwards and every past scan is re-judged with them.",
        "nav.signout": "Sign out",
        "login.title": "Sign in",
        "login.hint": "Enter the access token from your configuration.",
        "login.token": "Access token",
        "login.submit": "Continue",
        "login.bad": "That token does not match.",
        "manage.title": "Watchlist",
        "manage.lede": "What you save here is what the next scan uses. No file to edit.",
        "manage.add": "Add a company",
        "manage.edit_one": "Editing {id}",
        "manage.edit": "Edit",
        "manage.save": "Save",
        "manage.pause": "Pause",
        "manage.resume": "Resume",
        "manage.on": "Active",
        "manage.paused": "Paused",
        "manage.scan_all": "Queue a full scan",
        "manage.scan_one": "Scan",
        "manage.watching": "{n} companies watched",
        "manage.in_progress": "Run {run} in progress — {done}/{total}",
        "manage.field.id": "id",
        "manage.field.id_hint": "This keys the history. Set it once and leave it.",
        "manage.field.company_en": "Name in English",
        "manage.field.tier": "Tier",
        "manage.field.enabled": "Include in scans",
        "manage.field.urls_hint": "One per line. The first is the primary URL.",
        "manage.no_industries": "No industries yet",
        "manage.no_industries_hint": "Every company belongs to an industry. Add one below, or load the example watchlist from a terminal: radar watchlist import targets.yaml",
        "manage.industry_add": "Add an industry",
        "manage.industry_count": "{n} so far",
        "manage.industry_label": "Display name",
        "manage.robots": "robots.txt",
        "manage.robots.respect": "Follow the site's robots.txt (default)",
        "manage.robots.override": "Make an exception for this company",
        "manage.robots.reason": "Reason (required for an exception)",
        "manage.robots.hint": "An exception is a per-company decision and the reason is kept, so anyone can see later why it was made.",
        "manage.robots.respect_chip": "follows",
        "manage.robots.turned_away": "site says no",
        "manage.turned_away_note": "{n} companies are turning us away in robots.txt. If you have grounds to look anyway, make a per-company exception and record why.",
        "manage.robots.override_chip": "exception",
        "run.counts": "{done}/{total} done · {pending} queued · {running} running · {failed} failed",
        "run.waiting": "No worker has picked this up yet",
        "run.worker_hint": "This run's jobs are queued. Start a worker on whichever machine should run the browser.",
        "job.pending": "queued",
        "job.claimed": "running",
        "job.done": "done",
        "job.failed": "failed",
        "nav.ops": "Operations",
        "ops.title": "Operations",
        "ops.lede": "What used to need a terminal. The dashboard only leaves a request; a worker does the work.",
        "ops.worker.alive": "worker {name} · active {ago}s ago",
        "ops.worker.stale": "the worker is not responding · last seen {at}",
        "ops.worker.none": "no worker has checked in · see bin/radarctl status",
        "ops.scan": "Scan",
        "ops.scan.note": "Scans are queued; a worker visits the sites with a browser. Follow progress on the run page.",
        "ops.scan.due": "{n} due now",
        "ops.scan.tier": "{tier} · {n}",
        "ops.scan.all": "all {n}",
        "ops.scan.nothing": "nothing to scan right now",
        "ops.tasks": "Tasks",
        "ops.tasks.note": "Each button queues one task. Open its result in the list below.",
        "ops.task.digest": "Write a digest",
        "ops.task.digest.hint": "signals and run health, written to data/logs/",
        "ops.task.redetect": "Re-detect",
        "ops.task.redetect.hint": "re-judge every stored observation with the current fingerprints; no site is visited",
        "ops.task.notify": "Send notifications",
        "ops.task.notify.hint": "push signals not yet sent to the webhook",
        "ops.task.notify_dry": "Preview notifications",
        "ops.task.notify_dry.hint": "list what would be sent; send nothing",
        "ops.task.hygiene": "Watchlist hygiene",
        "ops.task.hygiene.hint": "URLs that keep failing — dead or moved domains",
        "ops.task.backup": "Back up the database",
        "ops.task.backup.hint": "snapshot into backups/, keeping 14",
        "ops.queued": "Task #{id} ({kind}) queued; a worker will pick it up shortly.",
        "ops.history": "Recent tasks",
        "ops.history.none": "No tasks yet.",
        "ops.runs": "Runs in progress",
        "task.kind.digest": "digest",
        "task.kind.redetect": "re-detect",
        "task.kind.notify": "notifications",
        "task.kind.hygiene": "watchlist hygiene",
        "task.kind.backup": "database backup",
        "task.state.pending": "queued",
        "task.state.running": "running",
        "task.state.done": "done",
        "task.state.failed": "failed",
        "task.title": "Task #{id} · {kind}",
        "task.requested": "requested {at} · {by}",
        "task.waiting": "Waiting for a worker to pick this up. This page refreshes itself.",
        "task.output": "Output",
        "task.no_output": "no output",
        "common.seconds": "s",
        "footer.readonly": "Verdicts come only from evidence · scans are queued and run by a worker",
        "common.all": "All",
        "common.none": "none",
        "common.company": "Company",
        "common.industry": "Industry",
        "common.vendor": "Vendor",
        "common.vendors": "Vendors",
        "common.companies": "Companies",
        "common.company_count": "Companies",
        "common.share": "Share",
        "common.state": "State",
        "common.change": "Change",
        "common.score": "Score",
        "common.time": "Time",
        "common.status": "Status",
        "common.run": "Run",
        "common.note": "Note",
        "common.layer": "Layer",
        "common.strength": "Strength",
        "common.pattern": "Pattern",
        "common.observed": "Observed value",
        "common.evidence_layers": "Evidence layers",
        "common.and_more": "+{n} more",
        "verdict.DETECTED": "Detected",
        "verdict.PROBABLE": "Probable",
        "state.NEW": "New",
        "state.REAPPEARED": "Reappeared",
        "state.STABLE": "Stable",
        "state.BASELINE": "Baseline",
        "state.REMOVAL_CANDIDATE": "Removal candidate",
        "state.REMOVED": "Removed",
        "status.OK": "OK",
        "status.BLOCKED": "Blocked",
        "status.TIMEOUT": "Timed out",
        "status.NAV_FAILED": "Unreachable",
        "status.BROWSER_ERROR": "Browser error",
        "status.THIN": "Interstitial page",
        "status.SKIPPED_BY_ROBOTS": "Skipped at the site's request",
        "status.PARTIAL": "Partial load (not comparable)",
        "status.unscanned": "never scanned",
        "kind.HOME_MIGRATION": "Replaced by a competitor",
        "kind.HOME_REMOVAL": "Our platform at risk",
        "kind.COMPETITOR_MIGRATION": "Vendor swap",
        "kind.COMPETITOR_REMOVAL": "Vendor leaving",
        "kind.GREENFIELD": "No platform — open",
        "kind.COMPETITOR_NEW": "Vendor arrived",
        "kind.HOME_NEW": "Our platform installed",
        "kind.HOST_CHANGED": "Landing site changed",
        "category.engagement": "engagement",
        "category.experimentation": "experimentation",
        "category.analytics": "analytics",
        "category.attribution": "attribution",
        "category.advertising": "advertising",
        "category.platform": "platform",
        "overview.latest_run": "Latest run <b>#{run}</b> · {when} · {scans} scans · {fingerprints} fingerprints",
        "overview.no_runs": "No runs yet. Start with <code>{command}</code>.",
        "overview.card.registered": "companies watched",
        "overview.card.holders": "have an engagement platform",
        "overview.card.greenfield": "greenfield",
        "overview.card.unjudged": "could not be judged",
        "overview.signals_all": "all {n} →",
        "overview.no_change": "No change signals.",
        "overview.by_industry": "By industry",
        "overview.engagement_share": "Engagement platform share",
        "overview.all_vendors": "all vendors →",
        "overview.col.holders": "Have one",
        "overview.col.greenfield": "Greenfield",
        "overview.col.unjudged": "Unjudged",
        "overview.col.held_vendors": "Platforms in use",
        "overview.statement": "Of {judged} companies judged, <em>{greenfield}</em> run their marketing without an engagement platform.",
        "overview.statement.empty": "Nothing judged yet. The summary appears once the first scan finishes.",
        "overview.signals_line": "{n} change signals",
        "companies.pick_industry": "All industries",
        "signals.title": "Signals",
        "signals.empty": "No signals match this filter.",
        "signals.maturity": "{total} MarTech tools · {advertising} ad · {analytics} analytics",
        "signals.maturity.attribution": " · {n} attribution",
        "signals.maturity.experimentation": " · {n} A/B",
        "signals.maturity.score": " · maturity {score}",
        "signals.change_detail": "{name} — {streak} run(s) in a row since run {since} (of {judged} judged runs)",
        "signals.quiet.title": "Below the bar",
        "signals.quiet.note": "No engagement platform, but too little MarTech to qualify as a lead. Listed rather than dropped — a threshold that hides accounts reads as \"we checked and found nothing\".",
        "signals.quiet.score": "maturity {score}",
        "signals.unjudged.title": "Could not be judged",
        "signals.unjudged.note": "Never scanned successfully, so no signal was produced. <b>This is not the same as greenfield.</b>",
        "companies.title": "{n} companies",
        "companies.filter.holders": "Has a platform",
        "companies.filter.greenfield": "Greenfield",
        "companies.filter.moved": "Changed",
        "companies.filter.unjudged": "Unjudged",
        "companies.none": "No companies match.",
        "companies.chip.greenfield": "none",
        "companies.chip.judged": "judged",
        "companies.chip.unjudged": "{status} · cannot judge",
        "companies.chip.paused": "monitoring paused",
        "companies.chip.off_domain": "Lands off-domain",
        "company.off_domain": "The latest good observation landed outside the watched URL's domain ({host}). The stack below may not be this company's. Check the watchlist URL.",
        "company.host_shift": "Since run {run} the landing moved from {previous} to {current}. Earlier history is not compared.",
        "common.landing": "Landing",
        "company.never_judged": "This company has never been scanned successfully (last: {status}). <b>No stack can be reported</b> — which is not the same as running nothing.",
        "company.signals": "Signals",
        "company.brief": "View brief",
        "company.brief.title": "{company} brief",
        "company.brief.note": "The complete list of facts an email may cite. Nothing outside it goes in.",
        "company.brief.unusable": "No usable observation, so there is no brief. Do not draft a cold email for this company.",
        "company.scan_now": "Scan now",
        "company.stack": "Current stack",
        "company.stack.summary": "{total} MarTech tools · maturity {score}",
        "company.stack.hint": "Expand any row to see the evidence behind the verdict.",
        "company.no_direct": "no direct evidence",
        "company.mention_only": "referenced only — not observed running",
        "company.seen_on": "seen on {url}",
        "company.streak": " · {streak} of {judged} judged runs in a row",
        "company.timeline": "Timeline",
        "company.timeline.excluded": "not judged — excluded from history",
        "company.scans": "Scan log",
        "company.col.urls": "URLs",
        "vendors.title": "Vendor share",
        "vendors.basis": "Across {n} successfully scanned companies.",
        "vendors.include_unseen": "include never-detected fingerprints",
        "vendor.detected_in": "detected at {n} companies",
        "vendor.users": "Companies using it",
        "vendor.fingerprint": "Fingerprint",
        "vendor.none": "This vendor has not been detected at any company yet.",
        "digest.title": "MarTech Deal Radar — {date}",
        "notify.header": "MarTech Radar — {n} new signal(s)",
        "ack.ack": "Ack",
        "ack.dismiss": "Dismiss",
        "ack.clear": "Clear",
        "ack.acked": "In progress",
        "ack.dismissed": "Dismissed",
        "ack.dismissed_count": "{n} dismissed signal(s) — show",
        "ack.hide_dismissed": "Hide dismissed",
        "digest.hygiene": "Repeatedly unreachable (check these domains, {n}):",
        "company.identifiers": "Account identifiers",
        "company.identifiers.note": "Vendor account IDs observed in scans — which contract, not just which vendor.",
        "brief.identifiers": "## Observed account identifiers",
        "notify.more": "…and {n} more (see the Signals page)",
        "digest.latest_run": "Latest run #{run} · {when} · {scans} scans ({statuses})",
        "digest.partial": " — **partial run**: {covered} of {total} watched companies scanned",
        "digest.partial_note": "The figures below use each company's **most recent good scan**, so a partial run does not distort them.",
        "digest.changes": "## Changes this week",
        "digest.no_changes": "- none",
        "digest.greenfield": "## Open accounts (no engagement platform · {n})",
        "digest.quiet": "## Below the bar (for reference)",
        "digest.unjudged": "## Could not be judged — not greenfield",
        "brief.unknown_target": "Unknown company id: {target_id!r}",
        "brief.never_scanned": "**Never scanned successfully.** ({scans} attempts, last: {status})",
        "brief.never_scanned.rule": "There is no observation to write from, so do not draft a cold email for this company.\nThis means \"we could not look\", not \"they run nothing\".",
        "brief.urls": "- URLs: {urls}",
        "brief.latest": "- Last good observation: {date} (run {run}), {judged} judged runs",
        "brief.host_shift": "- **Landing changed**: {previous} → {current} since run {run}. Earlier history is not compared",
        "brief.off_domain": "**The latest good observation (run {run}) landed outside the watched URL's domain ({host}).** It is not evidence about this company, so neither the stack nor any fact may be cited. Check the watchlist URL.",
        "brief.counts": "- {total} MarTech tools detected · maturity {score}",
        "brief.engagement": "## Engagement platform",
        "brief.engagement.none": "- **None (greenfield)** — absent in all {judged} judged runs",
        "brief.engagement.gone": "- **Not currently detected** — {name}: absent since run {since} ({state}, {streak} run(s) in a row of {judged} judged). Detected up to the run before.",
        "brief.stack": "## Observed stack",
        "brief.changes": "## Changes",
        "brief.changes.none": "- none — identical across {judged} judged runs",
        "brief.facts": "## Facts you may cite in the email",
        "brief.facts.rule": "These are what we actually observed. Anything not on this list does not go in the email.",
        "brief.fact.no_engagement": "- no engagement/CRM platform detected (all {judged} judged runs)",
        "brief.fact.engagement_gone": "- engagement platform {name} was detected until recently and has been absent since run {since} ({streak} run(s) in a row — a removal candidate, not confirmed)",
        "brief.fact.advertising": "- {n} advertising pixels running",
        "brief.fact.analytics": "- {n} analytics tools running",
        "brief.fact.attribution": "- {n} mobile attribution SDKs — suggests an app business alongside",
        "brief.fact.experimentation": "- {n} A/B testing tools — an experimentation habit exists",
        "brief.fact.no_experimentation": "- no A/B testing tool detected",
        "signal.home_removal.headline": "{vendor} absent for {streak} run(s) in a row",
        "signal.home_removal.unconfirmed": " (once — needs confirming)",
        "signal.home_removal.detail": "Absent since run {since}. ",
        "signal.home_removal.confirmed_note": "Past the confirmation threshold.",
        "signal.home_removal.candidate_note": "A candidate until the next run confirms it.",
        "signal.migration.headline": "{gone} → {arrived} swap",
        "signal.migration.unconfirmed": " (needs confirming)",
        "signal.migration.detail": "{gone} absent since run {gone_since}, {arrived} detected since run {arrived_since} — one left as the other arrived.",
        "signal.competitor_removal.headline": "{name} absent for {streak} run(s) in a row",
        "signal.competitor_removal.unconfirmed": " (needs confirming)",
        "signal.competitor_removal.detail": "Absent since run {since}. May be a replacement window.",
        "signal.arrival.headline": "{name} newly detected",
        "signal.host_changed.headline": "Landing moved from {previous} to {current}",
        "signal.host_changed.detail": "Lands on a different site since run {run}. Earlier history is not compared and no vendor-change signal is raised. Check the watchlist URL.",
        "signal.host_changed.off_domain": " It is also outside the watched URL's domain, so this may not be the company's site at all.",
        "signal.arrival.reappeared": " (returned)",
        "signal.arrival.detail": "Detected since run {since}; absent in the run before.",
        "signal.greenfield.headline": "No engagement platform · {total} MarTech tools running",
        "signal.greenfield.detail": "{advertising} advertising pixels, {analytics} analytics tools",
        "signal.greenfield.attribution": ", {n} attribution",
        "signal.greenfield.experimentation": ", {n} A/B",
    },
}


class MissingTranslation(KeyError):
    """Raised when a key exists in no catalogue at all."""


@lru_cache(maxsize=8)
def translator(language: str = DEFAULT_LANGUAGE) -> Callable[..., str]:
    """Return `t(key, **values)` for one language.

    Falls back to the default language for a key a translation has not
    reached yet, so a partial catalogue degrades to mixed text rather than
    to a crash on a page someone is looking at.
    """
    table = CATALOGUE.get(language) or CATALOGUE[DEFAULT_LANGUAGE]
    fallback = CATALOGUE[DEFAULT_LANGUAGE]

    def t(key: str, **values) -> str:
        template = table.get(key, fallback.get(key))
        if template is None:
            raise MissingTranslation(key)
        return template.format(**values) if values else template

    return t


def company_name(row, language: str = DEFAULT_LANGUAGE) -> str:
    """The name to show a reader in this language.

    Company names are data, not translations — but a watchlist that carries
    `company_en` is telling us what a non-Korean reader should see, and a
    global team reading a name in a script they cannot read learns nothing.
    """
    local = row["company"]
    if language == DEFAULT_LANGUAGE:
        return local
    try:
        english = row["company_en"]
    except (KeyError, IndexError):
        english = None
    return english or local


def languages() -> tuple[str, ...]:
    return tuple(CATALOGUE)


def missing_keys(language: str) -> list[str]:
    """Keys the default language has and this one does not."""
    return sorted(set(CATALOGUE[DEFAULT_LANGUAGE]) - set(CATALOGUE.get(language, {})))
